# File managed by pluginsync
pluginsync_config: '0.1.14'
managed_files:
- .github
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- .pluginsync.yml
- .travis.yml
- CONTRIBUTING.md
- LICENSE
- Makefile
- scripts
- scripts/common.sh
- scripts/deps.sh
- scripts/test
- scripts/test.sh
